---
- name: Process package list
  vars:
  block:
    - name: Clone model-driven-devops nso-oc-services repo
      ansible.builtin.git:
        repo: 'https://github.com/model-driven-devops/{{ item.name }}.git'
        dest: '/tmp/{{ item.name }}'
      with_items: "{{ mdd_model_repos }}"
    - name: Move models to packages directory
      command:
        cmd: 'mv /tmp/{{ item[0].name }}/{{ item[1] }} {{ nso_run_dir }}/packages'
      with_subelements:
        - "{{ mdd_model_repos }}"
        - model_list
    - name: Make packages
      command:
        chdir: '{{ nso_run_dir }}/packages/{{ item[1] }}/src/'
        cmd: '/bin/bash -c "source {{ nso_install_dir }}/ncsrc"; make'
      with_subelements:
        - "{{ mdd_model_repos }}"
        - model_list
    - name: Remove repo
      file:
        path: '/tmp/{{ item.name }}'
        state: absent
      with_items: "{{ mdd_model_repos }}"
  when: mdd_model_repos is defined