#---
## vars file for ansible-nso
#aws_access_key_id: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
#aws_secret_access_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
#aws_region: "{{ lookup('env','AWS_REGION') }}"
#aws_bucket: "{{ lookup('env','AWS_BUCKET') }}"